ShangOnline/ShangOnline/urls.py
from django.conf.urls import url,include
# from django.contrib import admin
import xadmin
from django.views.static import serve
from ShangOnline.settings import MEDIA_ROOT,STATIC_ROOT
from users.views import IndexView

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^ueditor/',include('DjangoUeditor.urls')),
    url(r'^$',IndexView.as_view(),name='index'),
    url(r'^captcha/',include('captcha.urls')),
    url(r'^static/(?P<path>.*)', serve, {'document_root': STATIC_ROOT}),
    url(r'^static/media/(?P<path>.*)',serve,{'document_root':MEDIA_ROOT}),
    url(r'^users/', include('users.urls',namespace='users')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^orgs/', include('orgs.urls', namespace='orgs')),
    url(r'^operations/', include('operations.urls', namespace='operations')),

]

ShangOnline/apps/courses/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import course_list,course_detail,course_video,course_comment
urlpatterns = [
    url(r'^course_list/$',course_list,name='course_list'),
    url(r'^course_detail/(\d+)/$', course_detail, name='course_detail'),
    url(r'^course_video/(\d+)/$', course_video, name='course_video'),
    url(r'^course_comment/(\d+)/$', course_comment, name='course_comment'),
]

ShangOnline/apps/operations/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import user_ask,user_love,user_comment,user_deletelove
urlpatterns = [
    url(r'^user_ask/$',user_ask,name='user_ask'),
    url(r'^user_love/$', user_love, name='user_love'),
    url(r'^user_comment/$', user_comment, name='user_comment'),
    url(r'^user_deletelove/$', user_deletelove, name='user_deletelove'),
]

ShangOnline/apps/orgs/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import org_list,org_detail,org_detail_course,org_detail_desc,org_detail_teacher,teacher_list,teacher_detail

urlpatterns = [
    url(r'^org_list/$',org_list,name='org_list'),
    url(r'^org_detail/(\d+)/$', org_detail, name='org_detail'),
    url(r'^org_detail_course/(\d+)/$', org_detail_course, name='org_detail_course'),
    url(r'^org_detail_desc/(\d+)/$', org_detail_desc, name='org_detail_desc'),
    url(r'^org_detail_teacher/(\d+)/$', org_detail_teacher, name='org_detail_teacher'),


    url(r'^teacher_list/$',teacher_list,name='teacher_list'),
    url(r'^teacher_detail/(\d+)/$', teacher_detail, name='teacher_detail'),
]

ShangOnline/apps/users/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import user_login,user_active,user_logout,user_forget,user_reset,user_info,user_changeimage,user_changeinfo,user_sendcode,user_changeemail,user_course,user_loveorg,user_loveteacher,user_lovecourse,user_message,user_readmessage,UserRegisterView
urlpatterns = [
    url(r'^user_register/$',UserRegisterView.as_view(),name='user_register'),
    url(r'^user_login/$', user_login, name='user_login'),
    url(r'^active/(\w+)/$', user_active, name='user_active'),
    url(r'^user_logout/$', user_logout, name='user_logout'),

    url(r'^user_forget/$', user_forget, name='user_forget'),
    url(r'^user_reset/(\w+)/$', user_reset, name='user_reset'),

    url(r'^user_info/$',user_info,name='user_info'),

    url(r'^user_changeimage/$', user_changeimage, name='user_changeimage'),

    url(r'^user_changeinfo/$', user_changeinfo, name='user_changeinfo'),

    url(r'^user_sendcode/$', user_sendcode, name='user_sendcode'),

    url(r'^user_changeemail/$', user_changeemail, name='user_changeemail'),

    url(r'^user_course/$', user_course, name='user_course'),

    url(r'^user_loveorg/$', user_loveorg, name='user_loveorg'),

    url(r'^user_loveteacher/$', user_loveteacher, name='user_loveteacher'),

    url(r'^user_lovecourse/$', user_lovecourse, name='user_lovecourse'),

    url(r'^user_message/$', user_message, name='user_message'),

    url(r'^user_readmessage/$', user_readmessage, name='user_readmessage'),
]

ShangOnline/extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

ShangOnline/apps/courses/models.py
from django.db import models
from datetime import datetime
from orgs.models import OrgInfo,TeacherInfo
from DjangoUeditor.models import UEditorField
# Create your models here.
class CourseInfo(models.Model):
    name = models.CharField(max_length=20,verbose_name="课程名称")
    desc = models.CharField(max_length=200,verbose_name="课程简介")
    detail = UEditorField(verbose_name='课程详情', width=700, height=400, toolbars='full',
                          imagePath='ueditor/images/', filePath='ueditor/files/',
                          upload_settings={'imageMaxSizing': 1024000},
                          default='')
    level = models.CharField(choices=(('初级','初级'),('中级','中级'),('高级','高级')),max_length=5,verbose_name="课程难度",default='初级')
    stunum = models.IntegerField(default=0,verbose_name="学习人数")
    study_time = models.IntegerField(default=0,verbose_name="学习时长")
    lesson_num = models.IntegerField(default=0,verbose_name="章节数")
    category = models.CharField(choices=(('前端','前端'),('后台','后台')),max_length=5,verbose_name="课程类别")
    click_num = models.IntegerField(default=0, verbose_name='点击数')
    love_num = models.IntegerField(default=0, verbose_name='收藏数')
    image = models.ImageField(upload_to='course/%y/%m',verbose_name="课程图片",max_length=100)
    orginfo = models.ForeignKey(OrgInfo,verbose_name="所属机构")
    teacherinfo = models.ForeignKey(TeacherInfo,verbose_name="所属讲师")
    need_know = models.CharField(max_length=100,verbose_name="课程须知",null=True,blank=True)
    teacher_say = models.CharField(max_length=200,verbose_name="老师告知",null=True,blank=True)
    is_banner = models.BooleanField(default=False,verbose_name="是否轮播")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.name


    class Meta:
        verbose_name = '课程信息'
        verbose_name_plural = verbose_name

class LessonInfo(models.Model):
    name = models.CharField(max_length=50,verbose_name="章节名称")
    courseinfo = models.ForeignKey(CourseInfo,verbose_name="所属课程")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '章节信息'
        verbose_name_plural = verbose_name

class VideoInfo(models.Model):
    name = models.CharField(max_length=50,verbose_name="视频名称")
    study_time = models.IntegerField(default=0,verbose_name='视频时长')
    url = models.URLField(default='http://video.atguigu.com/ce182d3e92d24c08ada798ed75236efe/64240d5f98c849d7a48a701646314ef0-abb0a550e0a4e1bd89390a178f91a577-ld.mp4',max_length=200,verbose_name='视频连接')
    lessoninfo = models.ForeignKey(LessonInfo,verbose_name="所属章节")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '视频信息'
        verbose_name_plural = verbose_name

class SourceInfo(models.Model):
    name = models.CharField(max_length=20,verbose_name="资源名称")
    file_addr = models.FileField(upload_to='source/%y/%m',verbose_name="资源地址",max_length=200)
    courseinfo = models.ForeignKey(CourseInfo,verbose_name='所属课程')
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '资源信息'
        verbose_name_plural = verbose_name

ShangOnline/apps/users/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class UserProfile(AbstractUser):
    nick_name = models.CharField(max_length=20,verbose_name="用户昵称",default='')
    birthday = models.DateField(null=True,blank=True,verbose_name="用户生日")
    gender = models.CharField(choices=(('girl','女'),('boy','男')),max_length=5,verbose_name="用户性别",default='girl')
    address = models.CharField(max_length=200,verbose_name="用户地址",null=True,blank=True)
    phone = models.CharField(max_length=11,verbose_name="用户手机",null=True,blank=True)
    image = models.ImageField(upload_to='user/%y/%m',verbose_name="用户头像",null=True,blank=True,max_length=100)
    is_start = models.BooleanField(default=False,verbose_name="是否激活")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.username

    def get_msg_count(self):
        from operations.models import UserMessageInfo
        return  UserMessageInfo.objects.filter(userinfo=self.id,msg_status=False).count()

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name

class EmailVerify(models.Model):
    email = models.EmailField(max_length=100,verbose_name="邮箱")
    code = models.CharField(max_length=20,verbose_name="验证码")
    send_type = models.CharField(choices=(('register','注册'),('forget','修改'),('changeemail','修改邮箱')),max_length=20,verbose_name='验证码类型')
    add_time = models.DateTimeField(default=datetime.now,verbose_name='发送时间')

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = '邮箱验证码'
        verbose_name_plural = verbose_name

class Banner(models.Model):
    image = models.ImageField(upload_to='banner/%y/%m',verbose_name="轮播图片",max_length=200)
    url = models.URLField(max_length=100,verbose_name="轮播图片链接",default='http://www.atguigu.com/')
    add_time = models.DateTimeField(default=datetime.now,verbose_name='添加时间')

    def __str__(self):
        return str(self.image)

    class Meta:
        verbose_name = '轮播图信息'
        verbose_name_plural = verbose_name



ShangOnline/apps/users/forms.py
#encoding=utf-8
#__Author__: weesmile
#__Date__: 2018-06-15
import re
from django import forms
from captcha.fields import CaptchaField
from .models import UserProfile,EmailVerify

class UserRegisterForm(forms.Form):

    email = forms.EmailField(required=True,error_messages={
        'required':'邮箱必须填写'
    })
    password = forms.CharField(min_length=3,max_length=20,required=True,error_messages={
        'required': '密码必须填写',
        'min_length':'密码最少得3个',
        'max_length': '密码最多20个',
    })
    captcha = CaptchaField(error_messages={
        'invalid':'验证码错误'
    })

class UserLoginForm(forms.Form):
    email=forms.EmailField(required=True,error_messages={
        'required':'邮箱必须填写'
    })
    password=forms.CharField(min_length=3,max_length=20,required=True,error_messages={
        'required':'密码必须填写',
        'max_length':'密码最多20个',
        "min_length":'密码最少3个'
    })


class UserForgetForm(forms.Form):
    email = forms.EmailField(required=True,error_messages={
        'required':'邮箱必须填写'
    })
    captcha = CaptchaField(error_messages={
        'invalid': '验证码错误'
    })

class UserResetForm(forms.Form):
    password = forms.CharField(min_length=3,max_length=20,required=True,error_messages={
        'required':'密码必须填写',
        'max_length':'密码最多20个',
        "min_length":'密码最少3个'
    })
    password1 = forms.CharField(min_length=3, max_length=20, required=True, error_messages={
        'required': '密码必须填写',
        'max_length': '密码最多20个',
        "min_length": '密码最少3个'
    })

class UserChangeImageform(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image']

class UserChangeInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['nick_name','birthday','gender','phone','address']

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        #1 创建正则对象
        com = re.compile('^(13\d|14[57]|15\d|166|17[367]|18\d)\d{8}$')
        if com.match(phone):
            return phone
        else:
            raise forms.ValidationError('手机验证不合法')

class UserSendCodeForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['email']

class UserChangeEmailForm(forms.ModelForm):
    class Meta:
        model = EmailVerify
        fields = ['email','code']

ShangOnline/templates/users/usercenter-fav-course.html
{% extends 'users/usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的收藏- 尚在线{% endblock %}
{% block breach %}
    我的收藏
{% endblock %}
{% block right %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'users:user_loveorg' %}">课程机构</a> </li>
                        <li><a href="{% url 'users:user_loveteacher' %}">授课教师 </a></li>
                        <li class="active"><a href="{% url 'users:user_lovecourse' %}">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for course in all_courses %}
                        <div class="module1_5 box">
                            <a href="{% url 'courses:course_detail' course.id %}">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'courses:course_detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.study_time }}</i></span>
                                <span class="fr">学习人数：{{ course.stunum }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.orginfo.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="12" love-id="{{ course.id }}"></span>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
{% endblock %}
{% block myjs1 %}
    <script>
        $(function () {
            $('.delete-group').click(function () {
                var loveid = $(this).attr('love-id');
                var lovetype = 2;
                var obj = $(this);
                $.ajax({
                    type:'GET',
                    url:'{% url 'operations:user_deletelove' %}',
                    data:{
                        loveid:loveid,
                        lovetype:lovetype
                    },
                    success:function (callback) {
                        if(callback.status == 'ok'){
                            obj.parents('.module1_5').remove()
                        }else {
                            alert('删除失败')
                        }
                    }
                })
            })
        })
    </script>
{% endblock %}


ShangOnline/templates/users/usercenter-fav-org.html
{% extends 'users/usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的收藏- 尚在线{% endblock %}
{% block breach %}
    我的收藏
{% endblock %}
{% block right %}
   <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>

            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="active"><a href="{% url 'users:user_loveorg' %}">课程机构</a> </li>
                        <li><a href="{% url 'users:user_loveteacher' %}">授课教师 </a></li>
                        <li><a href="{% url 'users:user_lovecourse' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for org in all_orgs %}
                    <div class="messages butler_list company company-fav-box" >
                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'orgs:org_detail' org.id %}">
                                    <img width="160" height="90" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="{% url 'orgs:org_detail' org.id %}">{{ org.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">

                                    <img src="{% static 'images/authentication.png' %}"/>


                                    <img src="{% static 'images/gold.png' %}"/>

                                </div>
                                <span class="c8 clear">{{ org.cityinfo.name }}</span>
                                <div class="delete " data-favid="2" love-id="{{ org.id }}"></div>
                            </dd>
                        </dl>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
{% endblock %}
{% block myjs1 %}
    <script>
        $(function () {
            $('.delete').click(function () {
                var loveid = $(this).attr('love-id');
                var lovetype = 1;
                var obj = $(this);
                $.ajax({
                    type:'GET',
                    url:'{% url 'operations:user_deletelove' %}',
                    data:{
                        loveid:loveid,
                        lovetype:lovetype
                    },
                    success:function (callback) {
                        if(callback.status == 'ok'){
                            obj.parents('.messages').remove()
                        }else {
                            alert('删除失败')
                        }
                    }
                })
            })
        })
    </script>
{% endblock %}

ShangOnline/templates/users/usercenter-fav-teacher.html
{% extends 'users/usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的收藏- 尚在线{% endblock %}
{% block breach %}
    我的收藏
{% endblock %}
{% block right %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'users:user_loveorg' %}">课程机构</a> </li>
                        <li class="active"><a href="{% url 'users:user_loveteacher' %}">授课教师 </a></li>
                        <li><a href="{% url 'users:user_lovecourse' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for teacher in all_teachers %}
                    <div class=" butler_list butler-fav-box">
                        <dl class="des users">
                            <dt>
                                <a href="{% url 'orgs:teacher_detail' teacher.id %}">
                                    <img width="100" height="100" src="{{ MEDIA_URL }}{{ teacher.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1>
                                    <a href="{% url 'orgs:teacher_detail' teacher.id %}">
                                        {{ teacher.name }}<span class="key">认证教师</span>
                                    </a>
                                </h1>
                                <ul class="cont clearfix">
                                    <li class="time">工作年限：<span>{{ teacher.work_year }}年</span></li>
                                    <li class="c7">课程数：<span>{{ teacher.courseinfo_set.count }}</span></li>
                                </ul>
                                <ul class="cont clearfix">
                                    <li class="time">工作公司：<span>{{ teacher.work_company }}</span></li>
                                    <li class="c7">公司职位：<span>{{ teacher.work_position }}</span></li>
                                </ul>
                            </dd>
                            <div class="delete jsDeleteFav_teacher" data-favid="1" love-id="{{ teacher.id }}"></div>
                        </dl>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
{% endblock %}
{% block myjs1 %}
    <script>
        $(function () {
            $('.delete').click(function () {
                var loveid = $(this).attr('love-id');
                var lovetype = 3;
                var obj = $(this);
                $.ajax({
                    type:'GET',
                    url:'{% url 'operations:user_deletelove' %}',
                    data:{
                        loveid:loveid,
                        lovetype:lovetype
                    },
                    success:function (callback) {
                        if(callback.status == 'ok'){
                            obj.parents('.butler_list').remove()
                        }else {
                            alert('删除失败')
                        }
                    }
                })
            })
        })
    </script>
{% endblock %}

ShangOnline/templates/users/usercenter-info.html
{% extends 'users/usercenter-base.html' %}
{% load staticfiles %}
{% block title %}个人信息- 尚在线{% endblock %}
{% block breach %}个人信息{% endblock %}
{% block right %}
    <div class="right">
		<div class="personal_des ">
			<div class="head" style="border:1px solid #eaeaea;">
				<h1>个人信息</h1>
			</div>
			<div class="inforcon">
				<div class="left" style="width:242px;">
                    <iframe id='frameFile' name='frameFile' style='display: none;'></iframe>
                    <form class="clearfix" id="jsAvatarForm" enctype="multipart/form-data" autocomplete="off" method="post" action="{% url 'users:user_changeimage' %}" target='frameFile'>
                        {% csrf_token %}
                        <label class="changearea" for="avatarUp">
                            <span id="avatardiv" class="pic">
                                <img width="100" height="100" class="js-img-show" id="avatarShow" src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                            </span>
                            <span class="fl upload-inp-box" style="margin-left:70px;">
                                <span class="button btn-green btn-w100" id="jsAvatarBtn">修改头像</span>
                                <input type="file" name="image" id="avatarUp" class="js-img-up"/>
                            </span>
                        </label>
                    </form>
                    <div style="border-top:1px solid #eaeaea;margin-top:30px;">
                        <a class="button btn-green btn-w100" id="jsUserResetPwd" style="margin:80px auto;width:100px;">修改密码</a>
                    </div>
				</div>
				<form class="perinform" id="jsEditUserForm" autocomplete="off">
					<ul class="right">
						<li>昵&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;称：
                           <input type="text" name="nick_name" id="nick_name" value="{{ request.user.nick_name|default_if_none:'' }}" maxlength="10">
                            <i class="error-tips"></i>
                        </li>
						<li>生&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;日：
                           <input type="text" id="birth_day" name="birday" value="{{ request.user.birthday|default_if_none:'' }}" readonly="readonly"/>
                            <i class="error-tips"></i>
						</li>
						<li>性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别：
							<label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio"  name="gender" value="boy" {% if request.user.gender == 'boy' %}checked="checked"{% endif %}>男</label>
							<label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="gender" value="girl" {% if request.user.gender == 'girl' %}checked="checked"{% endif %}>女</label>
						</li>
						<li class="p_infor_city">地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;址：
                            <input type="text" name="address" id="address" placeholder="请输入你的地址" value="{{ request.user.address|default_if_none:'' }}" maxlength="10">
						    <i class="error-tips"></i>
                        </li>
						<li>手&nbsp;&nbsp;机&nbsp;&nbsp;号：
                            <input type="text" name="mobile" id="mobile" placeholder="请输入你的手机号码" value="{{ request.user.phone|default_if_none:'' }}" maxlength="11">
                        </li>
                        <li>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱：
                        	<input class="borderno" type="text" name="email" readonly="readonly" value="{{ request.user.email }}"/>
                            <span class="green changeemai_btn">[修改]</span>
                    	</li>
						<li class="button heibtn">
							<input type="button" id="jsEditUserBtn" value="保存">
						</li>
					</ul>
				</form>
			</div>
		</div>
	</div>
{% endblock %}
{% block dialog %}
<div class="dialog" id="jsDialog">
    <div class="resetpwdbox dialogbox" id="jsResetDialog">
        <h1>修改密码</h1>
        <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
        <div class="cont">
            <form id="jsResetPwdForm" autocomplete="off">
                <div class="box">
                    <span class="word2" >新&nbsp;&nbsp;密&nbsp;&nbsp;码</span>
                    <input type="password" id="pwd" name="password1" placeholder="6-20位非中文字符"/>
                </div>
                <div class="box">
                    <span class="word2" >确定密码</span>
                    <input type="password" id="repwd" name="password2" placeholder="6-20位非中文字符"/>
                </div>
                <div class="error btns" id="jsResetPwdTips"></div>
                <div class="button">
                    <input id="jsResetPwdBtn" type="button" value="提交" />
                </div>
                <input type='hidden' name='csrfmiddlewaretoken' value='DaP7IUKm9FA9nELA9YUlYYWpyIDdCiIP' />
            <input type='hidden' name='csrfmiddlewaretoken' value='799Y6iPeEDNSGvrTu3noBrO4MBLv6enY' />
            </form>
        </div>
    </div>
    <div class="dialogbox changeemai1 changephone" id="jsChangeEmailDialog">
        <h1>修改邮箱</h1>
        <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
        <p>请输入新的邮箱地址</p>
        <form id="jsChangeEmailForm" autocomplete="off">
            <div class="box">
                <input class="fl change_email" name="email" id="jsChangeEmail" type="text" placeholder="输入重新绑定的邮箱地址">
            </div>
            <div class="box">
                <input class="fl email_code" type="text" id="jsChangeEmailCode" name="code" placeholder="输入邮箱验证码">
                <input class="getcode getting" type="button" id="jsChangeEmailCodeBtn" value="获取验证码">
            </div>
            <div class="error btns change_email_tips" id="jsChangeEmailTips" >请输入...</div>
            <div class="button">
                <input class="changeemai_btn" id="jsChangeEmailBt" type="button" value="完成"/>
            </div>
        </form>
    </div>
</div>
<div class="bg" id="dialogBg"></div>
{% endblock %}

{% block myjs1 %}
    <script src="{% static 'js/deco-user.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
    <script>
        $(function () {
            $('#jsEditUserBtn').click(function () {
                var nick_name = $('#nick_name').val();
                var birthday = $('#birth_day').val();
                var gender = $(':checked').val();
                var address = $('#address').val();
                var phone = $('#mobile').val();
                $.ajax({
                    type:'POST',
                    url:'{% url 'users:user_changeinfo' %}',
                    data:{
                        nick_name:nick_name,
                        birthday:birthday,
                        gender:gender,
                        address:address,
                        phone:phone,
                        csrfmiddlewaretoken:'{{ csrf_token }}',
                    },
                    success:function (callback) {
                        if(callback.status == 'ok'){
                            window.location.reload()
                        }else {
                            alert(callback.msg)
                        }
                    }
                })
            });
            $('#jsChangeEmailCodeBtn').click(function () {
                var email = $('#jsChangeEmail').val();
                $.ajax({
                    type:'POST',
                    url:'{% url 'users:user_sendcode' %}',
                    data:{
                        email:email,
                        csrfmiddlewaretoken:'{{ csrf_token }}'
                    },
                    success:function (callback) {
                        alert(callback.msg)
                    }
                })
            });
            $('#jsChangeEmailBt').click(function () {
                var email = $('#jsChangeEmail').val();
                var code = $('#jsChangeEmailCode').val();
                $.ajax({
                    type:'POST',
                    url:'{% url 'users:user_changeemail' %}',
                    data:{
                        email:email,
                        code:code,
                        csrfmiddlewaretoken:'{{ csrf_token }}'
                    },
                    success:function (callback) {
                        if (callback.status == 'ok'){
                            alert(callback.msg);
                            window.location.href = '{% url 'users:user_logout' %}';
                        }else {
                            alert(callback.msg);
                        }
                    }
                })
            })
        })
    </script>
{% endblock %}