ShangOnline/ShangOnline/urls.py
from django.conf.urls import url,include
# from django.contrib import admin
import xadmin
from django.views.static import serve
from ShangOnline.settings import MEDIA_ROOT,STATIC_ROOT
from users.views import IndexView

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^ueditor/',include('DjangoUeditor.urls')),
    url(r'^$',IndexView.as_view(),name='index'),
    url(r'^captcha/',include('captcha.urls')),
    url(r'^static/(?P<path>.*)', serve, {'document_root': STATIC_ROOT}),
    url(r'^static/media/(?P<path>.*)',serve,{'document_root':MEDIA_ROOT}),
    url(r'^users/', include('users.urls',namespace='users')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^orgs/', include('orgs.urls', namespace='orgs')),
    url(r'^operations/', include('operations.urls', namespace='operations')),

]

ShangOnline/apps/courses/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import course_list,course_detail,course_video,course_comment
urlpatterns = [
    url(r'^course_list/$',course_list,name='course_list'),
    url(r'^course_detail/(\d+)/$', course_detail, name='course_detail'),
    url(r'^course_video/(\d+)/$', course_video, name='course_video'),
    url(r'^course_comment/(\d+)/$', course_comment, name='course_comment'),
]

ShangOnline/apps/operations/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import user_ask,user_love,user_comment,user_deletelove
urlpatterns = [
    url(r'^user_ask/$',user_ask,name='user_ask'),
    url(r'^user_love/$', user_love, name='user_love'),
    url(r'^user_comment/$', user_comment, name='user_comment'),
    url(r'^user_deletelove/$', user_deletelove, name='user_deletelove'),
]

ShangOnline/apps/orgs/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import org_list,org_detail,org_detail_course,org_detail_desc,org_detail_teacher,teacher_list,teacher_detail

urlpatterns = [
    url(r'^org_list/$',org_list,name='org_list'),
    url(r'^org_detail/(\d+)/$', org_detail, name='org_detail'),
    url(r'^org_detail_course/(\d+)/$', org_detail_course, name='org_detail_course'),
    url(r'^org_detail_desc/(\d+)/$', org_detail_desc, name='org_detail_desc'),
    url(r'^org_detail_teacher/(\d+)/$', org_detail_teacher, name='org_detail_teacher'),


    url(r'^teacher_list/$',teacher_list,name='teacher_list'),
    url(r'^teacher_detail/(\d+)/$', teacher_detail, name='teacher_detail'),
]

ShangOnline/apps/users/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import user_login,user_active,user_logout,user_forget,user_reset,user_info,user_changeimage,user_changeinfo,user_sendcode,user_changeemail,user_course,user_loveorg,user_loveteacher,user_lovecourse,user_message,user_readmessage,UserRegisterView
urlpatterns = [
    url(r'^user_register/$',UserRegisterView.as_view(),name='user_register'),
    url(r'^user_login/$', user_login, name='user_login'),
    url(r'^active/(\w+)/$', user_active, name='user_active'),
    url(r'^user_logout/$', user_logout, name='user_logout'),

    url(r'^user_forget/$', user_forget, name='user_forget'),
    url(r'^user_reset/(\w+)/$', user_reset, name='user_reset'),

    url(r'^user_info/$',user_info,name='user_info'),

    url(r'^user_changeimage/$', user_changeimage, name='user_changeimage'),

    url(r'^user_changeinfo/$', user_changeinfo, name='user_changeinfo'),

    url(r'^user_sendcode/$', user_sendcode, name='user_sendcode'),

    url(r'^user_changeemail/$', user_changeemail, name='user_changeemail'),

    url(r'^user_course/$', user_course, name='user_course'),

    url(r'^user_loveorg/$', user_loveorg, name='user_loveorg'),

    url(r'^user_loveteacher/$', user_loveteacher, name='user_loveteacher'),

    url(r'^user_lovecourse/$', user_lovecourse, name='user_lovecourse'),

    url(r'^user_message/$', user_message, name='user_message'),

    url(r'^user_readmessage/$', user_readmessage, name='user_readmessage'),
]

ShangOnline/extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

ShangOnline/apps/courses/models.py
from django.db import models
from datetime import datetime
from orgs.models import OrgInfo,TeacherInfo
from DjangoUeditor.models import UEditorField
# Create your models here.
class CourseInfo(models.Model):
    name = models.CharField(max_length=20,verbose_name="课程名称")
    desc = models.CharField(max_length=200,verbose_name="课程简介")
    detail = UEditorField(verbose_name='课程详情', width=700, height=400, toolbars='full',
                          imagePath='ueditor/images/', filePath='ueditor/files/',
                          upload_settings={'imageMaxSizing': 1024000},
                          default='')
    level = models.CharField(choices=(('初级','初级'),('中级','中级'),('高级','高级')),max_length=5,verbose_name="课程难度",default='初级')
    stunum = models.IntegerField(default=0,verbose_name="学习人数")
    study_time = models.IntegerField(default=0,verbose_name="学习时长")
    lesson_num = models.IntegerField(default=0,verbose_name="章节数")
    category = models.CharField(choices=(('前端','前端'),('后台','后台')),max_length=5,verbose_name="课程类别")
    click_num = models.IntegerField(default=0, verbose_name='点击数')
    love_num = models.IntegerField(default=0, verbose_name='收藏数')
    image = models.ImageField(upload_to='course/%y/%m',verbose_name="课程图片",max_length=100)
    orginfo = models.ForeignKey(OrgInfo,verbose_name="所属机构")
    teacherinfo = models.ForeignKey(TeacherInfo,verbose_name="所属讲师")
    need_know = models.CharField(max_length=100,verbose_name="课程须知",null=True,blank=True)
    teacher_say = models.CharField(max_length=200,verbose_name="老师告知",null=True,blank=True)
    is_banner = models.BooleanField(default=False,verbose_name="是否轮播")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.name


    class Meta:
        verbose_name = '课程信息'
        verbose_name_plural = verbose_name

class LessonInfo(models.Model):
    name = models.CharField(max_length=50,verbose_name="章节名称")
    courseinfo = models.ForeignKey(CourseInfo,verbose_name="所属课程")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '章节信息'
        verbose_name_plural = verbose_name

class VideoInfo(models.Model):
    name = models.CharField(max_length=50,verbose_name="视频名称")
    study_time = models.IntegerField(default=0,verbose_name='视频时长')
    url = models.URLField(default='http://video.atguigu.com/ce182d3e92d24c08ada798ed75236efe/64240d5f98c849d7a48a701646314ef0-abb0a550e0a4e1bd89390a178f91a577-ld.mp4',max_length=200,verbose_name='视频连接')
    lessoninfo = models.ForeignKey(LessonInfo,verbose_name="所属章节")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '视频信息'
        verbose_name_plural = verbose_name

class SourceInfo(models.Model):
    name = models.CharField(max_length=20,verbose_name="资源名称")
    file_addr = models.FileField(upload_to='source/%y/%m',verbose_name="资源地址",max_length=200)
    courseinfo = models.ForeignKey(CourseInfo,verbose_name='所属课程')
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '资源信息'
        verbose_name_plural = verbose_name

ShangOnline/apps/orgs/models.py
from django.db import models
from datetime import datetime
from DjangoUeditor.models import UEditorField
# Create your models here.
class CityInfo(models.Model):
    name = models.CharField(max_length=50,verbose_name="城市名称")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '城市信息'
        verbose_name_plural = verbose_name


class OrgInfo(models.Model):
    name = models.CharField(max_length=20,verbose_name="机构名称")
    image = models.ImageField(upload_to='org/%y/%m',verbose_name="机构图片",max_length=100)
    study_num = models.IntegerField(default=0,verbose_name="学习人数")
    address = models.CharField(max_length=200,verbose_name="机构地址")
    click_num = models.IntegerField(default=0,verbose_name="点击数")
    love_num = models.IntegerField(default=0, verbose_name="收藏数")
    desc = models.CharField(max_length=200,verbose_name='机构简介')
    detail = UEditorField(verbose_name='机构详情',width=700,height=400,toolbars='full',imagePath='ueditor/images/',filePath='ueditor/files/',upload_settings={'imageMaxSizing':1024000},default='')
    course_num = models.IntegerField(default=0,verbose_name="课程数量")
    cityinfo = models.ForeignKey(CityInfo,verbose_name='所属城市')
    category = models.CharField(choices=(('jg','机构'),('gx','高校'),('gr','个人')),max_length=5,verbose_name="机构类别",null=True,blank=True)
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '机构信息'
        verbose_name_plural = verbose_name


class TeacherInfo(models.Model):
    name = models.CharField(max_length=20,verbose_name="讲师姓名")
    image = models.ImageField(upload_to='teacher/%y/%m',verbose_name="讲师头像",null=True,blank=True,max_length=200)
    work_year = models.IntegerField(default=3,verbose_name="工作年限")
    work_company = models.CharField(max_length=20,verbose_name="就职公司",null=True,blank=True)
    work_position = models.CharField(max_length=20,verbose_name="工作职位",null=True,blank=True)
    age = models.IntegerField(default=30,verbose_name="讲师年龄")
    work_style = models.CharField(max_length=20,verbose_name="教学特点",null=True,blank=True)
    click_num = models.IntegerField(default=0, verbose_name="点击数")
    love_num = models.IntegerField(default=0, verbose_name="收藏数")
    orginfo = models.ForeignKey(OrgInfo,verbose_name="所属机构")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '讲师信息'
        verbose_name_plural = verbose_name




ShangOnline/apps/orgs/views.py
from django.shortcuts import render
from .models import OrgInfo,TeacherInfo,CityInfo
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from operations.models import UserLoveInfo
from django.db.models import Q
# Create your views here.
def org_list(request):
    #拿到所有的数据
    all_orgs = OrgInfo.objects.all()
    all_citys = CityInfo.objects.all()

    keywords = request.GET.get('keywords', '')
    if keywords:
        all_orgs = all_orgs.filter(Q(name__icontains=keywords) | Q(desc__icontains=keywords)|Q(detail__icontains=keywords))

    #获取机构的排序
    sort_orgs = all_orgs.order_by('-add_time')[:3]

    #根据类别过滤
    cat = request.GET.get('cat','')
    if cat:
        all_orgs = all_orgs.filter(category=cat)

    #根据城市过滤
    cityid = request.GET.get('cityid','')
    if cityid:
        all_orgs = all_orgs.filter(cityinfo_id = int(cityid))


    #排序
    sort = request.GET.get('sort','')
    if sort == 'studynum':
        all_orgs = all_orgs.order_by('-study_num')
    if sort == 'coursenum':
        all_orgs = all_orgs.order_by('-course_num')


    pagenum = request.GET.get('pagenum',1)
    pa = Paginator(all_orgs,2)
    try:
        page_list = pa.page(pagenum)
    except PageNotAnInteger:
        page_list = pa.page(1)
    except EmptyPage:
        page_list = pa.page(pa.num_pages)

    return render(request,'orgs/org-list.html',{
        'all_orgs':all_orgs,
        'all_citys':all_citys,
        'page_list':page_list,
        'cat':cat,
        'cityid':cityid,
        'sort':sort,
        'sort_orgs':sort_orgs,
        'keywords': keywords
    })

def org_detail(request,org_id):
    if org_id:
        org = OrgInfo.objects.filter(id = int(org_id))[0]
        org.click_num += 1
        org.save()
        is_love = False
        if request.user.is_authenticated():
            love = UserLoveInfo.objects.filter(userinfo=request.user,love_type=1,love_id=int(org_id))
            if love:
                is_love = love[0].love_status
            else:
                pass


        return render(request,'orgs/org-detail-homepage.html',{
            'org':org,
            'detail_type':'homepage',
            'is_love':is_love
        })

def org_detail_course(request,org_id):
    if org_id:
        org = OrgInfo.objects.filter(id = int(org_id))[0]
        is_love = False
        if request.user.is_authenticated():
            love = UserLoveInfo.objects.filter(userinfo=request.user, love_type=1, love_id=int(org_id))
            if love:
                is_love = love[0].love_status
            else:
                pass
        return render(request,'orgs/org-detail-course.html',{
            'org':org,
            'detail_type': 'course',
            'is_love': is_love
        })

def org_detail_desc(request,org_id):
    if org_id:
        org = OrgInfo.objects.filter(id = int(org_id))[0]
        is_love = False
        if request.user.is_authenticated():
            love = UserLoveInfo.objects.filter(userinfo=request.user, love_type=1, love_id=int(org_id))
            if love:
                is_love = love[0].love_status
            else:
                pass
        return render(request,'orgs/org-detail-desc.html',{
            'org':org,
            'detail_type': 'desc',
            'is_love': is_love
        })

def org_detail_teacher(request,org_id):
    if org_id:
        org = OrgInfo.objects.filter(id = int(org_id))[0]

        is_love = False
        if request.user.is_authenticated():
            love = UserLoveInfo.objects.filter(userinfo=request.user, love_type=1, love_id=int(org_id))
            if love:
                is_love = love[0].love_status
            else:
                pass


        return render(request,'orgs/org-detail-teachers.html',{
            'org':org,
            'detail_type': 'teacher',
            'is_love': is_love
        })

def teacher_list(request):
    # print(request.path)
    all_teachers = TeacherInfo.objects.all()
    rec_teachers = all_teachers.order_by('-click_num')[:2]

    keywords = request.GET.get('keywords', '')
    if keywords:
        all_teachers = all_teachers.filter(name__icontains=keywords)

    sort_type = request.GET.get('sort','')
    if sort_type == 'hot':
        all_teachers = all_teachers.order_by('-love_num')
    pagenum = request.GET.get('pagenum', 1)
    pa = Paginator(all_teachers, 2)
    try:
        page_list = pa.page(pagenum)
    except PageNotAnInteger:
        page_list = pa.page(1)
    except EmptyPage:
        page_list = pa.page(pa.num_pages)

    return render(request,'orgs/teachers-list.html',{
        'all_teachers':all_teachers,
        'page_list':page_list,
        'sort_type':sort_type,
        'rec_teachers':rec_teachers,
        'keywords':keywords

    })

def teacher_detail(request,teacher_id):
    all_teachers = TeacherInfo.objects.all()
    rec_teachers = all_teachers.order_by('-click_num')[:2]
    if teacher_id:
        teacher = all_teachers.filter(id = int(teacher_id))[0]
        teacher.click_num += 1
        teacher.save()

        is_love = False
        is_loveTeacher = False
        if request.user.is_authenticated():
            love = UserLoveInfo.objects.filter(userinfo=request.user,love_type=1,love_id=teacher.orginfo.id)
            love1 = UserLoveInfo.objects.filter(userinfo=request.user, love_type=3, love_id=teacher.id)
            if love:
                is_love = love[0].love_status
            if love1:
                is_loveTeacher = love1[0].love_status



        return render(request,'orgs/teacher-detail.html',{
            'teacher':teacher,
            'rec_teachers':rec_teachers,
            'is_love':is_love,
            'is_loveTeacher':is_loveTeacher
        })

ShangOnline/templates/orgs/org-detail-desc.html
{% extends 'orgs/org_detail_base.html' %}
{% block title %}机构介绍详情页--尚在线{% endblock %}
{% block breach %}机构介绍{% endblock %}
{% block right %}
    <div class="right companycenter layout" >
        <div class="head">
            <h1>机构介绍</h1>
        </div>
        <div class="des">
            {{ org.detail|safe }}
{#            {% autoescape off %}#}
{#                {{ org.detail }}#}
{#            {% endautoescape %}#}
        </div>
    </div>
{% endblock %}




ShangOnline/templates/orgs/org_detail_base.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block mycss %}
   <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% block mycss1 %}{% endblock %}

{% endblock %}
{% block search %}
<div class="middle companyheader">
        <div class="wp">
            <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ org.image }}"/>
            <div class="head fl">
                <h1>
                    尚在线网
                    <img src="{% static 'images/authentication.png' %}"/>
                    <img src="{% static 'images/gold.png' %}"/>
                </h1>
                <p class="fl">
                    <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                    <span class="precision company-credit" data-star-scope="5.0"></span>
                    <span class="key">5.0</span>
                </p>
            </div>
            <div class="btn fr collectionbtn  notlogin" data-favid="22" data-fav-type="1" id="love">
                 {% if is_love %}取消收藏{% else %}收藏{% endif %}
            </div>

        </div>
    </div>
{% endblock %}
{% block content %}
<section>
	<div class="wp">
		<ul  class="crumbs">
            <li><a href="/">首页</a>></li>
			<li><a href="{% url 'orgs:org_list' %}">课程机构</a>></li>
			<li>{% block breach %}{% endblock %}</li>
		</ul>
	</div>
</section>

<section>
<div class="wp list personal_list comp">
		<div class="left">
			<ul>
				<li {% if detail_type == 'homepage' %}class="active2"{% endif %}><a href="{% url 'orgs:org_detail' org.id %}">机构首页</a></li>
                <li {% if detail_type == 'course' %}class="active2"{% endif %}><a href="{% url 'orgs:org_detail_course' org.id %}">机构课程</a></li>
                <li {% if detail_type == 'desc' %}class="active2"{% endif %}><a href="{% url 'orgs:org_detail_desc' org.id %}">机构介绍</a></li>
                <li {% if detail_type == 'teacher' %}class="active2"{% endif %}><a href="{% url 'orgs:org_detail_teacher' org.id %}">机构讲师</a></li>
			</ul>
		</div>

{% block right %}

{% endblock %}
 </div>
</section>
{% endblock %}
{% block myjs %}
<script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
<script type="text/javascript">
$(function () {
   $('#love').click(function () {
       {#  attr 和 prop 两种操作标签属性的方法，#}
       {#区别：attr是用来取或者设置自定义的属性#}
       {#      prop是用来取或者设置标签自带的属性#}
        var lovetype = $('#love').attr('data-fav-type');
        var loveid = {{ org.id }}
       $.ajax({
           type:'GET',
           url:'{% url 'operations:user_love' %}',
           data:{
               lovetype:lovetype,
               loveid:loveid
           },
           success:function (callback) {
                if(callback.status == 'ok'){
                    $('#love').text(callback.msg)
                }else if(callback.status=='nologin'){
                    window.location.href = "{% url 'users:user_login' %}"
                }else {
                    alert(callback.msg)
                }
           }

       })
   })
});
$(function(){
    var $precision = $('.precision'),
        score = $precision.attr('data-star-scope'),
        option =  {
                    half		: true,
                    path		: '{% static 'images/' %}',
                    precision	: true,
                    size		: 24,
                    starOff		: 'g_star.png',
                    starOn		: 'r_star.png',
                    starHalf	: 'h_star.png',
                    hints       : ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg  : '暂时还未获得评价！',
                    readOnly    : true,
                    score       : score
                };
    $precision.raty(option);

    $('.jsFavBtn').on('click', function(){
        var type = $(this).attr('data-fav-type');
        if(type == '1'){
            favPraise($(this), 'fav' ,1 , '收藏');

        }else if(type == '3'){
            favPraise($(this), 'fav' ,3 );

        }else if(type == '11'){
            favPraise($(this), 'pra', 1);

        }else if(type == '4'){
            favPraise($(this), 'fav' ,4 );

        }
    });
})
</script>


<script type="text/javascript">
$(function() {
    $('.recordbtn1').click(function(){
        $('.recordbox1').show();
    });
    $('.recordbtn2').click(function(){
        $('.recordbox2').show();
    });

    $('.imgslide').unslider({
        speed: 500,               //  The speed to animate each slide (in milliseconds)
        delay: 3000,              //  The delay between slide animations (in milliseconds)
        complete: function() {},  //  A function that gets called after every slide animation
        keys: true,               //  Enable keyboard (left, right) arrow shortcuts
        dots: true,               //  Display dot navigation
        fluid: false              //  Support responsive design. May break non-responsive designs
    });
    var unslider = $('.imgslide').unslider();
    $('.unslider-arrow').click(function() {
        var fn = this.className.split(' ')[1];
        unslider.data('unslider')[fn]();
    });
});
</script>
    {% block myjs1 %}{% endblock %}
{% endblock %}
{% block footer %}{% endblock %}

ShangOnline/templates/orgs/teacher-detail.html
{% extends 'base.html' %}
{% block title %}讲师详情 - 尚在线{% endblock %}
{% block content %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="/">首页</a>></li>
                <li><a href="{% url 'orgs:teacher_list' %}">授课讲师</a>></li>
                <li>讲师详情</li>
            </ul>
        </div>
    </section>
    <section>
	<div class="wp butler-detail-box butler-diaryd-box clearfix">
        <div class="fl list">
            <div class="butler_detail_list clearfix">
                <div class="brief">
                    <dl class="des">
                        <dt>
                            <div class="picpic">
                                <img width="100" height="100" src="{{ MEDIA_URL }}{{ teacher.image }}"/>
                            </div>
                            <div class="btn">
                                <span class="fl btn1 collectionbtn" id="jsLeftBtn"  data-fav-type="3">
                                     {% if is_loveTeacher %}取消收藏{% else %}收藏{% endif %}
                                </span>
                                <span class="fr btn2 shareBtn bdsharebuttonbox"
                                      data-text="授课教师-李老师-慕学网"
                                      data-desc="我在#尚在线网#发现了"
                                      data-comment="李老师，工作年限：5年；学历：本科；所在公司：阿里巴巴&nbsp;；经典案例：django入门和深入；flask入门"
                                      data-url="/diary/hk_detail/10/">
                                    <span class="fl">分享</span>
                                    <a href="#" class="bds_more" data-cmd="more"></a>
                                </span>
                            </div>
                        </dt>
                        <dd>
                            <a href="#">
                                <h1>{{ teacher.name }}<span class="key picbig">金牌讲师</span></h1>
                            </a>
                            <ul class="cont">
                                <li>工作年限：<span>{{ teacher.work_year }}年</span></li>
                                <li>就职公司：<span>{{ teacher.work_company }}</span></li>
                                <li>工作职位：<span>{{ teacher.work_position }}&nbsp;</span></li>
                                <li>教学特点：<span>{{ teacher.work_style }}</span></li>
                            </ul>
                        </dd>
                    </dl>
                </div>
            </div>
            <div class="butler_detail_cont clearfix">
                <div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li class="active"><a href="{% url 'courses:course_list' %}">全部课程</a> </li>
					</ul>
				</div>
                    <div class="companycenter">
                        <div class="group_list brief">
                        {% for course in teacher.courseinfo_set.all %}
                            <div class="module1_5 box">
                                <a href="{% url 'courses:course_detail' course.id %}">
                                    <img width="214" height="190" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'courses:course_detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                    <span class="fl">时长：<i class="key">{{ course.study_time }}</i></span>
                                    <span class="fr">学习人数：{{ course.stunum }}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl">{{ course.orginfo.name }}</span>
                                    <span class="star fr  notlogin" data-favid="15">{{ course.love_num }}</span>
                                </div>
                            </div>
                        {% endfor %}
                        </div>
                    </div>
                <!--<div class="pageturn">-->
                    <!--<ul class="pagelist">-->
                        <!--<li class="active"><a href="?page=1">1</a></li>-->
                    <!--</ul>-->
                <!--</div>-->
            </div>
            </div>
        </div>
        <div class="fr list">
             <div class="butler_detail_list">
                <div class="right butler-company-box">
                <div class="head">
                    <h1>尚在线网</h1>
                    <p>知名高校，权威教学</p>
                </div>
                <div class="pic">
                    <a href="{% url 'orgs:org_detail' teacher.orginfo.id %}">
                        <img width="150" height="80" src="{{ MEDIA_URL }}{{ teacher.orginfo.image }}"/>
                    </a>
                </div>
                <a href="{% url 'orgs:org_detail' teacher.orginfo.id %}">
                    <h2 class="center">{{ teacher.orginfo.name }}</h2>
                </a>
                <p class="center tell">地址：{{ teacher.orginfo.address }}</p>
                <a class="btn" id="jsRightBtn" data-fav-type="1">
                    {% if is_love %}取消收藏{% else %}收藏{% endif %}
                </a>
            </div>
            </div>
            <div class="butler_detail_cont">
                <div class="butler_list_box">
                    <div class="right layout">
                        <div class="head">讲师排行榜</div>
                    {% for teacher1 in rec_teachers %}
                        <dl class="des">
                            <span class="num fl">{{ forloop.counter }}</span>
                            <a href="{% url 'orgs:teacher_detail' teacher1.id %}">
                                <dt>
                                    <img width="50" height="50" class="scrollLoading" src="{{ MEDIA_URL }}{{ teacher1.image }}"/>
                                </dt>
                            </a>
                            <dd>
                                <a href="{% url 'orgs:teacher_detail' teacher1.id %}">
                                    <h1 title="weesmile">{{ teacher1.name }}</h1>
                                </a>
                                <p>工作年限：<span>{{ teacher1.work_year }}年</span></p>
                            </dd>
                        </dl>
                    {% endfor %}
                    </div>
                </div>
            </div>
        </div>
	</div>
</section>
{% endblock %}
{% block myjs %}
    <script>
        $(function () {
            $('#jsRightBtn').click(function () {
                var loveid = {{ teacher.orginfo.id }};
                var lovetype = $(this).attr('data-fav-type');
                $.ajax({
                    type:'GET',
                    url:'{% url 'operations:user_love' %}',
                    data:{
                        loveid:loveid,
                        lovetype:lovetype
                    },
                    success:function (callback) {
                        if(callback.status == 'ok'){
                            $('#jsRightBtn').text(callback.msg)
                        }else {
                            alert(callback.msg)
                        }
                    }
                })
            });
            $('#jsLeftBtn').click(function () {
                var loveid = {{ teacher.id }};
                var lovetype = $(this).attr('data-fav-type');
                $.ajax({
                    type:'GET',
                    url:'{% url 'operations:user_love' %}',
                    data:{
                        loveid:loveid,
                        lovetype:lovetype
                    },
                    success:function (callback) {
                        if(callback.status == 'ok'){
                            $('#jsLeftBtn').text(callback.msg)
                        }else {
                            alert(callback.msg)
                        }
                    }
                })
            });
        })
    </script>
{% endblock %}